#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  5 21:26:06 2020

@author: chenguanlin
"""
import time as T
import random as r


def main2():
    
        str1='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
        global a,t1
        a=r.choice(str1)+r.choice(str1)+r.choice(str1)+r.choice(str1)+r.choice(str1)
        print('倒數三秒開始')
        print('3')
        T.sleep(1)
        print('2')
        T.sleep(1)
        print('1')
        T.sleep(1)
        print('第%d題:'%(t),end='')
        print(str(a))
        t1=T.time()
        game()
    

def main1():
    
        str1='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
        global a,t1
        a=r.choice(str1)+r.choice(str1)+r.choice(str1)+r.choice(str1)+r.choice(str1)       
        print('第%d題:'%(t),end='')
        print(str(a))
        t1=T.time()
        game()
   
        
def game():  
    b=str(input('Ans:'))
    
    if str(a)==str(b):
        t2=T.time()
        print('用了%.2f秒'%(t2-t1))        
        c=str(input('繼續？y or n: '))
        if c=='y':
            global t
            t+=1
            main2()
        elif c=='n': 
            print('結束!下次見:)')
            
    else:
        print('error')
        game()
#-------------------------------------------------
boolean=True
print('規則:')
print('打出跟題目一樣的字後按enter 看你反應多快')
start=input('開始遊戲？y or n: ')
if start=='y':
    t=int(0)
    t+=1
    print('倒數五秒開始')
    print('5')
    T.sleep(1)
    print('4')
    T.sleep(1)
    print('3')
    T.sleep(1)
    print('2')
    T.sleep(1)
    print('1')
    T.sleep(1)
    main1()
elif start=='n':
    print('掰掰')
else:
    print('錯誤')

        
        
