#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  9 02:04:26 2020

@author: chenguanlin
"""
import pygame
import sympy as sp
import time as T
import os
from sympy import diff,integrate,expand,symbols
pygame.init()
x,y,t=symbols("x y t")
def cal():
    cal=pygame.display.set_mode((640,320))
    pygame.display.set_caption("微積分計算機")
    
    background=pygame.surface(cal.get.size())
    background=background.convert()
    background.fill((255,255,255))
    cal.blit(background,(0,0))
    pygame.display.update()

running=True
while running:
    cal()
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            running=False
pygame.quit()
