#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 26 21:28:14 2020

@author: chenguanlin
"""



from sympy import diff,Symbol,integrate


x=Symbol("x")

print("微分請輸入dif \n積分請輸入int \n停止請輸入stop")

while(True):
    
    choose=input('****微分或積分****\n輸入:')
    
    if choose=='stop':
        print("結束")
        break
    
    elif choose=='help':
        print('救命\n 1.乘方用**,ex:x**2代表x平方\n ')
    
    
    #微分
    elif choose=='dif':  
        a=str(diff(input('請輸入函數(輸入0結束)f(x):'),x))
        print('f\'(x)=%s'%(a.replace('**','^').replace('*','')))
        
        
    
    
    #積分
    elif choose=='int':       
        b=str(integrate(input('請輸入函數(輸入0結束)f(x):') ,x))
        print('F(x)=%s'%(b.replace('**','^').replace('*','')))
        
    
    
    else:
        print("錯誤，請重新輸入")
