#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  4 01:29:18 2020

@author: chenguanlin
"""


def check():
    if(pw.get()=="213"):
        
        msg.set('correct')
    else:
        msg.set('error')
        
import tkinter as tk

win=tk.Tk()
pw=tk.StringVar()
msg=tk.StringVar()

label=tk.Label(win,text="input:")
label.pack()

entry=tk.Entry(win,textvariable=pw)
entry.pack()

button=tk.Button(win,text="in",command=check)
button.pack()

lmsg=tk.Label(win,fg="red",textvariable=msg)
lmsg.pack()

win.mainloop()
