#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 26 21:28:14 2020

@author: chenguanlin
"""



from sympy import diff,integrate,expand,symbols
x,y=symbols("x y")

#加入更多變數以應付偏微分,多重積分


print("微分請輸入dif \n積分請輸入int \n偏微分請輸入par \n二重積分請輸入dou \n多重積分請輸入mul(待更新) \n停止請輸入stop \n輸入help來看提示")
#嘗試寫偏微分,多重積分

             

while(True):
   
    choose=input('****請輸入功能****\n輸入:')
    
    if choose=='stop':
        print("結束!")
        break
    
    elif choose=='help':
        print('*****小抄*****')
        print('1.乘方用 ^。ex:x^2代表x平方')
        print('2.三角函數:sin,cos,tan,sec,csc,cot')
        print('3.自然對數exp(x)表示e的x次方')
    #提示之後要加的備忘錄
    #無限用oo表示
    #pi代表圓周率
    #sqrt()代表開根號 
    #I 代表sqrt(-1)
    #log()轉ln()
    #erf()=誤差函數
    #避免輸入a 因為程式碼會將a改成arc表示反三角函數
    #如果有複雜的代換法先代換,否則程式會死給你看
    
    #微分 differentiation
    elif choose=='dif':
        a=str(expand(diff(input('微分,請輸入函數f(x):').replace('^','**'),x)))
        print('f\'(x)=%s'%(a.replace('**','^').replace('*','').replace('a','arc').replace('log','ln')))
        
    #加偏微分pratial derivatives,程式會自動將不是所求的偏導數當成一般常數計算,可以加入梯度座標 ▽ｆ(nabla f)＝偏x i+偏y j,i j為向量
    elif choose=='par':
        
        listnum=[]
        listvar=[]
        par=str(input('偏微分,請輸入函數f(x):').replace('^','**'))
        n=int(input('要對幾個變數做偏微分:'))
        for n in range(1,n+1):
            
            num=str(input('對第%d個變數的偏導數:'%(n)))
            listnum.append(num)
            e=str(expand(diff(par,num)))
            listvar.append(e)
        print('▽f={ ',end='')
        for a in range(n-1):
            
            print('(%s),'%(listvar[a].replace('**','^').replace('*','').replace('a','arc').replace('log','ln')),end="")
        print('(%s) }'%(listvar[n-1].replace('**','^').replace('*','').replace('a','arc').replace('log','ln')))
        
        
       
            
      
    #不定積分&定積分   ∫ 
    #ind=indefinite integration. def=definite integration
    
    elif choose=='int':

        print('不定積分請輸入ind \n定積分請輸入def \n****不定積分或定積分****')
        intchoose=input('輸入:')
        if intchoose=='ind':
            b=str(expand(integrate(input('不定積分,請輸入函數f(x):').replace('^','**') ,x)))
            print('F(x)=%s+C'%(b.replace('**','^').replace('*','').replace('a','arc').replace('log','ln').replace('Integrarcl', '自己算，程式跑不動惹(先做代換後再輸入)ＱＱ➝➝')))
        elif intchoose=='def':
            print('請輸入函數f(x)以及積分上下限')
            c=str(expand(integrate(input('請輸入函數f(x):').replace('^','**'), (x,str(input('下限:')),str(input('上限:'))))))
             #判斷瑕積分(improper integral)
            print('Ans: %s'%(c.replace('**','^').replace('*','').replace('a','arc').replace('log','ln')))
        
                
        else:
            print('錯誤')
            
            
     #multiple integrals
    elif choose=='dou' :
        fubini=input('先對誰做積分？y or x:')
        if fubini=='y':
            d1=str(integrate(input('二重積分,請輸入函數f(x,y):'),(y,input('y下限:'),input('y上限:')),(x,input('x下限:'),input('x上限:'))))
            print('\nAns: %s'%(d1.replace('**','^').replace('*','').replace('a','arc').replace('log','ln')))
        elif fubini=='x':
            d2=str(integrate(input('二重積分,請輸入函數f(x,y):'),(x,input('x下限:'),input('x上限:')),(y,input('y下限:'),input('y上限:'))))
            print('\nAns: %s'%(d2.replace('**','^').replace('*','').replace('a','arc').replace('log','ln')))
        
        
    #新增fubini theorem,再寫一個if else
        
    
    #新增多重積分
    #構想：用for迴圈選擇幾重積分,然後重複積分上去,變數要自己輸入,記得用str轉資料型態
    
    else:
        print("錯誤，請重新輸入")
        



            
            
            
            
