#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 26 21:28:14 2020

@author: chenguanlin
"""



from sympy import diff,Symbol,integrate


x=Symbol("x")

print("微分請輸入dif \n積分請輸入int \n停止請輸入stop \n輸入help來看提示")

while(True):
    
    choose=input('****微分或積分****\n輸入:')
    
    if choose=='stop':
        print("結束")
        break
    
    elif choose=='help':
        print('*****小抄*****\n 1.乘方用 ^。ex:x^2代表x平方\n 2.三角函數:sin,cos,tan,sec,csc,cot\n 3.自然對數exp(x)表示e的x次方\n ')
    
    
    #微分
    elif choose=='dif':
        a=str(diff(input('請輸入函數(輸入0結束)f(x):').replace('^','**'),x))
        print('f\'(x)=%s'%(a.replace('**','^').replace('*','')))
        
        
    
    
    #不定積分
    elif choose=='int':       
        b=str(integrate(input('請輸入函數(輸入0結束)f(x):').replace('^','**') ,x))
        print('F(x)=%s+C'%(b.replace('**','^').replace('*','')))
        
    
    
    else:
        print("錯誤，請重新輸入")
